# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "omniauth-sharefile"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["backstitch Inc."]
  s.date = "2014-07-31"
  s.email = "admin@backstit.ch"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "RELEASE_NOTES.md",
    "Rakefile",
    "VERSION",
    "lib/omniauth-sharefile.rb",
    "lib/omniauth-sharefile/version.rb",
    "lib/omniauth/strategies/sharefile.rb",
    "omniauth-sharefile.gemspec"
  ]
  s.homepage = "http://github.com/backstitch/omniauth-sharefile"
  s.licenses = ["Proprietary"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "Sharefile Omniauth stratagy"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<omniauth>, [">= 0"])
      s.add_runtime_dependency(%q<omniauth-oauth2>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["= 2.14.1"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<omniauth>, [">= 0"])
      s.add_dependency(%q<omniauth-oauth2>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 2.14.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<omniauth>, [">= 0"])
    s.add_dependency(%q<omniauth-oauth2>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 2.14.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end
